### ISSUE TITLE
Some readings returned by API as strings; not supported by Pence or KWH classes

### ISSUE THREAD

**Issue by SimonPickup** [cybermaggedon/pyglowmarkt#15]
I am getting this error:
```
glowmarkt-dump --username user@example.com --password 'redacted' -m 240 -d PT1H
Entity: DCC Sourced
  gas cost:
    2023-04-24 01:00:00: 0.00 p
    2023-04-24 02:00:00: 0.00 p
    2023-04-24 03:00:00: 0.00 p
    2023-04-24 04:00:00: 0.00 p
    2023-04-24 05:00:00: 0.00 p
    current: Current reading not returned
    meter reading: Not implemented.
must be real number, not str
Traceback (most recent call last):
  File "/opt/homebrew/bin/glowmarkt-dump", line 76, in <module>
    raise e
  File "/opt/homebrew/bin/glowmarkt-dump", line 69, in <module>
    t.current_rates.rate,
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/glowmarkt/glowmarkt.py", line 21, in __str__
    return "%.2f p" % self.value
           ~~~~~~~~~^~~~~~~~~~~~
TypeError: must be real number, not str
```

PR coming, which supports any JSON values being either string or number.

**Comment by SimonPickup** [comment]
Current data for my gas:
```
{'status': 'OK', 'name': 'gas cost', 'resourceTypeId': 'redacted', 'resourceId': 'redacted', 'data': [{'cid': 'GAS', 'commodity': 'GAS', 'utility': 'HILD', 'name': 'fromDCC', 'from': '2023-04-09 00:00:00', 'plan': [{'planDetail': [{'standing': '27.47'}, {'ratem3': 116.021, 'rate': '10.34'}], 'note': 'This is a legacy structure and is due to be deprecated after transition.'}], 'structure': [{'planDetail': [{'standing': '27.47'}, {'rate': '10.34', 'ratem3': 116.021}]}], 'currentRates': {'standingCharge': '27.47', 'rate': '10.34'}, 'id': 780769, 'type': 'flatrate'}], 'classifier': 'gas.consumption.cost'}
```
